const express = require("express")
const { connect } = require("./config/db")
require("dotenv").config({ path: ".env" })
const cors = require("cors")
connect()
const app = express()
app.use(cors())
app.use(express.json())
app.use(express.static("public"))
app.use("/user", require("./routes/userRoutes"))
app.use("/doc", require("./routes/docRoutes"))
app.listen(process.env.PORT, console.log(`http://localhost:5000`))